monitoring_enabled: false
monitoring_prometheus_listen_address: 127.0.0.1
monitoring_prometheus_port: 9090
monitoring_prometheus_scrape_interval: 15s
monitoring_node_exporter_listen_address: 127.0.0.1
monitoring_node_exporter_port: 9100
monitoring_grafana_enabled: false
monitoring_grafana_port: 3000
monitoring_prometheus_retention: 15d
monitoring_grafana_admin_user: admin
monitoring_grafana_admin_password: admin
monitoring_grafana_domain: localhost
monitoring_grafana_root_url: "http://localhost:3000"

monitoring_eth_alerts_enabled: true
monitoring_lighthouse_min_peers: 8
monitoring_nethermind_min_peers: 8
monitoring_lighthouse_syncing_expr: "sync_eth2_synced == 0"
monitoring_lighthouse_peers_expr: "libp2p_peers < {{ monitoring_lighthouse_min_peers }}"
monitoring_nethermind_peers_expr: "ethereum_peer_count < {{ monitoring_nethermind_min_peers }}"

monitoring_alertmanager_enabled: false
monitoring_alertmanager_listen_address: 127.0.0.1
monitoring_alertmanager_port: 9093
monitoring_alertmanager_webhook_url: ""

nethermind_metrics_enabled: false
nethermind_metrics_host: 127.0.0.1
nethermind_metrics_port: 6060

lighthouse_metrics_enabled: false
lighthouse_metrics_address: 127.0.0.1
lighthouse_beacon_metrics_port: 5054
lighthouse_validator_metrics_port: 5064
