- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: restart node exporter
  systemd:
    name: prometheus node exporter
    state: restarted

- name: restart grafana
  systemd:
    name: grafana server
    state: restarted

- name: restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
